#include <iostream>

using namespace std;

// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

// Seems like brute force ought to solve this just fine.

int main()
{
    unsigned s1 = 1;
    unsigned s2 = 2;
    unsigned sum = 0;
    for (unsigned s = s2; s < 4000000; s = s1 + s2, s1 = s2, s2 = s) {
        if (s < 100) {
            cout << s << endl;
        }
        if (s % 2 == 0) {
            sum += s;
        }
    }

    cout << "The sum of even Fibonacci numbers less than 4,000,000 is " << sum << endl;
}
